### ISSUE TITLE
Include battery percentage settings

### ISSUE THREAD

**Issue by albfan** [albfan/gnome-tweak-tool#2]
battery percentage settings were added but not exposed

contact IRC: #gimpnet hadess

**Comment by allanday** [comment]
The key is /org/gnome/desktop/interface/show-battery-percentage

**Comment by albfan** [comment]
https://bugzilla.gnome.org/show_bug.cgi?id=769598

Suggestions to add that to g-c-c (gnome control center) on that issue

**Comment by albfan** [comment]
Seems this is done already

https://bugzilla.gnome.org/show_bug.cgi?id=783241

See point 9

thanks @jbicha

**Comment by albfan** [comment]
This is just suggested on that issue. Not done at all

**Comment by albfan** [comment]
Put final patch on https://bugzilla.gnome.org/show_bug.cgi?id=769598

**Comment by albfan** [comment]
Cannot run new changes. After compile on jhbuild I get this error:

```
$ jhbuild run gnome-tweak-tool
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
CRITICAL: Could not find schema /home/alberto/jhbuild/install/share/glib-2.0/schemas/org.gnome.shell.gschema.xml
WARNING : Shell not installed or running

(gnome-tweak-tool:2772): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: not a number

(gnome-tweak-tool:2772): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: Expected a string.

(gnome-tweak-tool:2772): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:832:10: not a number

(gnome-tweak-tool:2772): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:832:24: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(gnome-tweak-tool:2772): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1985:14: not a number

(gnome-tweak-tool:2772): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1985:14: Expected a string.

(gnome-tweak-tool:2772): Gtk-WARNING **: Theme parsing error: nautilus.css:55:71: Using one color stop with linear-gradient() is deprecated.

(gnome-tweak-tool:2772): Gtk-WARNING **: Theme parsing error: nautilus.css:56:71: Using one color stop with linear-gradient() is deprecated.
Gtk-Message: Failed to load module "canberra-gtk-module"
WARNING : Shell not running
None
WARNING : Error detecting shell
Traceback (most recent call last):
  File "/home/alberto/jhbuild/install/lib/python2.7/site-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 210, in __init__
    raise Exception("Shell not running or DBus service not available")
Exception: Shell not running or DBus service not available
Traceback (most recent call last):
  File "/home/alberto/jhbuild/install/lib/python2.7/site-packages/gtweak/app.py", line 42, in do_activate
    self.win = Window(self, model)
  File "/home/alberto/jhbuild/install/lib/python2.7/site-packages/gtweak/tweakview.py", line 59, in __init__
    self._model.load_tweaks(self)
  File "/home/alberto/jhbuild/install/lib/python2.7/site-packages/gtweak/tweakmodel.py", line 129, in load_tweaks
    mods = __import__("gtweak.tweaks", globals(), locals(), tweak_files, 0)
  File "/home/alberto/jhbuild/install/lib/python2.7/site-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 271, in <module>
    ShellExtensionTweakGroup(),
  File "/home/alberto/jhbuild/install/lib/python2.7/site-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 238, in __init__
    shell._settings.bind("disable-user-extensions", self.titlebar_widget,
AttributeError: 'NoneType' object has no attribute '_settings'
```

I already asked on https://riot.im/app/#/room/#_gimpnet_#control-center:matrix.org for help

**Comment by albfan** [comment]
Added dev hints to https://wiki.gnome.org/Apps/GnomeTweakTool/DevTips

Finally working and patch added to:

https://bugzilla.gnome.org/show_bug.cgi?id=769598#c2

This issue is finished here. Any further action continues on bugzilla and gimpnet
